### ISSUE TITLE
Error at install YouTube mp3 downloader 

### ISSUE THREAD

**Issue by sarowarhosen03** [ytb2mp3/youtube-mp3-downloader#104]
Am seeing this error when am trying to install 

`reify:youtube-mp3-downloader: http
> ffmpeg-static@4.4.0 install
> node install.js

ffmpeg-static install failed: No binary found for architecture
npm ERR! code 1
npm ERR! path /data/data/com.termux/files/home/Node/youtube-transcripts/node_modules/ffmpeg-static
npm ERR! command failed
npm ERR! command sh -c node install.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /data/data/com.termux/files/home/.npm/_logs/2022-05-26T10_54_24_070Z-debug-0.log`

**Comment by ytb2mp3** [comment]
This is an upstream error apparently, closing.
