### ISSUE TITLE
Videos with colons results in file name halts

### ISSUE THREAD

**Issue by Seralyne** [ytb2mp3/youtube-mp3-downloader#11]
When downloading a video with a ":" in it, the file name halts it's output when that happens, so for example: Emotional OST of the Day(Day51): Steins;Gate - Solitude will result in "Emotional OST of the Day(Day51) being downloaded, which, in turn has some implication for another thing I'm implementing this into.

**Comment by tobilg** [comment]
Works for me without problem. The file is saved as `Emotional Ost of the Day(Day 51): Steins;Gate - Solitude.mp3`. `youtube-mp3-downloader` doesn't replace colons.

**Comment by Seralyne** [comment]
http://i.imgur.com/kzVKVBF.png - This is a list of files downloaded files using a bot. Explorer shows them as having 0 bytes of data, ie. being empty, though clicking on properties reveals that they downloaded "properly", they also play properly through the bot I've implemented it in, but cause it to crash afterwards, which is a bug with that API. It only happens with files with a colon in them.

**Comment by tobilg** [comment]
So, you're using Windows? Then I guess colons are not allowed in file names... You can add a replace rule for that in https://github.com/tobilg/youtube-mp3-downloader/blob/master/lib/YoutubeMp3Downloader.js#L65

 I can release a new version not earlier than next week.

**Comment by tobilg** [comment]
I just pushed a new version (0.4.2) to NPM, which replaces also colons and semicolons.
