### ISSUE TITLE
What do i put in the ffmpegPath field?

### ISSUE THREAD

**Issue by MaragiDev** [ytb2mp3/youtube-mp3-downloader#112]
i have tryed the node package location but i cant figure it out.

**Comment by MaragiDev** [comment]
![image](https://user-images.githubusercontent.com/62991832/224572924-bb8a3e88-418e-4983-834e-069f7631a05b.png)

**Comment by MaragiDev** [comment]
always getting this error

**Comment by MaragiDev** [comment]
![image](https://user-images.githubusercontent.com/62991832/224572991-fcf38469-d36e-40bf-8a93-14c9ee01fda3.png)

**Comment by MaragiDev** [comment]
got ffmpeg in there

**Comment by MaragiDev** [comment]
![image](https://user-images.githubusercontent.com/62991832/224575394-5c958a68-4d05-4245-9bda-5a6eb0df1151.png)

**Comment by MaragiDev** [comment]
what am i doing wrong? hello

**Comment by ytb2mp3** [comment]
If you'd have read https://github.com/ytb2mp3/youtube-mp3-downloader#prerequisites you'd be able to answer this yourself. This is not your free tech support.
