### ISSUE TITLE
Downloading speed is low.

### ISSUE THREAD

**Issue by curly-hub** [ytb2mp3/youtube-mp3-downloader#12]
Hello,

I have an issue about the downloading speed, is pretty low even if my downloading speed is very high. There is anything in the code that makes hinders the speed?

Thank you.

**Comment by tobilg** [comment]
You should try setting the `youtubeVideoQuality` to `high` instead of `highest` (by default).

Also, you can monitor the `progress` event to see the actual download speed:

```
YD.on("progress", function(progress) {
    console.log(progress);
});
```

Other than that I can't really give you any hints.
