### ISSUE TITLE
YD.Download() throwing ECONNREFUSED Error

### ISSUE THREAD

**Issue by dohdoh64** [ytb2mp3/youtube-mp3-downloader#15]
When I use the example script to try to get an MP3 when it reaches YD.Download() it throws an error stating:
``connect ECONNREFUSED 127.0.0.1:80``
I have tried troubleshooting but I cannot figure out why it isn't working.

**Comment by tobilg** [comment]
The example doesn't do calls to 127.0.0.1 on port 80. So what exactly have you changed?

**Comment by dohdoh64** [comment]
I don't believe I changed anything, but I deleted and re-installed youtube-mp3-downloader and it now works.
