### ISSUE TITLE
Could not extract signature deciphering actions

### ISSUE THREAD

**Issue by syberlioz** [ytb2mp3/youtube-mp3-downloader#17]
Getting this error, also referenced here: https://github.com/fent/node-ytdl-core/issues/158

Error occurs on all videos for me as well. Thanks!

**Comment by tobilg** [comment]
I just release version `0.5.0`, see https://github.com/tobilg/youtube-mp3-downloader/releases/tag/0.5.0

**Comment by syberlioz** [comment]
Excellent, thanks.
