### ISSUE TITLE
ffmpeg exited with code 1

### ISSUE THREAD

**Issue by DonikaV** [ytb2mp3/youtube-mp3-downloader#20]
hi, i have installed your plugin.

Here us what i am try

```
var express = require('express');
var router = express.Router();
const path = require('path');
var YoutubeMp3Downloader = require("youtube-mp3-downloader");
const saveFolder = path.join(__dirname, '../public/uploads');


router.get('/', function(req, res, next) {
    //Configure YoutubeMp3Downloader with your settings
    var YD = new YoutubeMp3Downloader({
        "ffmpegPath": "/usr/local/Cellar/ffmpeg/3.4/bin/ffmpeg",        // Where is the FFmpeg binary located?
        "outputPath": saveFolder,    // Where should the downloaded and encoded files be stored?
        "youtubeVideoQuality": "highest",       // What video quality should be used?
        "queueParallelism": 2,                  // How many parallel downloads/encodes should be started?
        "progressTimeout": 2000                 // How long should be the interval of the progress reports
    });

    //Download video and save as MP3 file
    YD.download("omzk3klIy0E");

    YD.on("finished", function(err, data) {
        console.log(JSON.stringify(data));
    });

    YD.on("error", function(error) {
        console.warn('error');
        console.warn(error);
    });

    YD.on("progress", function(progress) {
        console.log(JSON.stringify(progress));
    });

});

module.exports = router;
```

in terminal i have:

GET /upload - - ms - -
error
ffmpeg exited with code 1: /Users/donika/Sites/slim-ytb/public/uploads/Major Lazer - Sua Cara (feat. Anitta & Pabllo Vittar) (Official Music Video).mp3: No such file or directory

error
ffmpeg exited with code 1: /Users/donika/Sites/slim-ytb/public/uploads/Major Lazer - Sua Cara (feat. Anitta & Pabllo Vittar) (Official Music Video).mp3: No such file or directory

GET /upload - - ms - -
error
ffmpeg exited with code 1: /Users/donika/Sites/slim-ytb/public/uploads/Major Lazer - Sua Cara (feat. Anitta & Pabllo Vittar) (Official Music Video).mp3: No such file or directory

Can you help me with this?

**Comment by DonikaV** [comment]
sorry, it was problem with permission. All works fine, thanks :)

**Comment by umang-govil** [comment]
After changing the permission of the outputPath folder, i am still getting the same 'ffmpeg exited with code 1' error.
Can you help me with this ?
