### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by DonikaV** [ytb2mp3/youtube-mp3-downloader#21]
Hi, nice plugin. 
How i can implement progress bar?
```
self.YD.on("progress", function(progress) {
		console.log(JSON.stringify(progress));
	});
```
How i can send it to the client side? Should i send file via xhr??

**Comment by tobilg** [comment]
Sorry, I can’t do individual project support. Have a look at socket.io

**Comment by DonikaV** [comment]
I didn't ask you about full implementation:) Maybe just suggestions ;)

9 дек. 2017 г. 10:24 пользователь "Tobi" <notifications@github.com> написал:

**Comment by DonikaV** [comment]
Also, it can't download large files... App goes down and nothing happens. Maybe I need change some settings of app? 
In console I see that it starting download several times and percentage wrong...

**Comment by tobilg** [comment]
I don’t know what you’re doing, and as I said, I can’t support individual projects. Try the sample code with the video that crashed in your app. If that works, it’s your code.

**Comment by DonikaV** [comment]
I use code from sample and didn't change anything. Only path to ffmpeg.
