### ISSUE TITLE
Unable to upload to Heroku

### ISSUE THREAD

**Issue by avj2352** [ytb2mp3/youtube-mp3-downloader#29]
Hi Team,

I was able to get the library locally on my windows machine using ffmpeg.exe.

Any idea how to upload this to heroku ?

**Comment by ytb2mp3** [comment]
Please use the Heroku docs to find out how you can use binary dependencies. This is not an issue of this nom module itself.

Either use Docker and https://devcenter.heroku.com/articles/container-registry-and-runtime or something like https://github.com/kontentcore/heroku-buildpack-ffmpeg
