### ISSUE TITLE
ffmpeg crash when using max queueParalellism

### ISSUE THREAD

**Issue by JugglerMaster** [ytb2mp3/youtube-mp3-downloader#32]
ffmpeg exits with code 1 and async.js throws an error that "Callback was already called"

When I increase the queue max I can run more instances but I cannot reach this max or else it will error out. This only crashes the program after the conversion is complete and just seems like a bug.

Error message:
https://pastebin.com/sBB0hbz1

Here's my code that I'm currently using:
https://pastebin.com/ncED4DhN

Any help with this would be much appreciated and the only reason I figured this out is I am running it on a raspberry pi 1 so I set the max queue to 1 and it crashed every time. 

Linux Raspbian version: 6.3.0-18
ffmpeg version: 3.2.12-1
nodejs version: 1.4.21

**Comment by JugglerMaster** [comment]
After playing around with the queue size it doesn't seem to affect the crash.

**Comment by JugglerMaster** [comment]
I was able to get a temporary fix by disabling error checking for ffmpeg in YoutubeMp3Downloader.js on line 142. I just commented out that line("callback(err.message, null);") and did a "console.log(err.message);" so I can still see there was an error and it doesn't return the error too many times and crash the application.

**Comment by ytb2mp3** [comment]
Does this problem still persist in the latest version @JugglerMaster?
