### ISSUE TITLE
Error: Status code: 403

### ISSUE THREAD

**Issue by IH3lios** [ytb2mp3/youtube-mp3-downloader#33]
The package is no longer functional. My web server keeps crashing every time I try to use the module due to a failing dependency.

![error](https://user-images.githubusercontent.com/33207396/59968577-b545b700-9509-11e9-93b7-0b8a53c5e027.png)

**Comment by sebastianprem** [comment]
Update the **ytdl-core** dependency to version 0.29.2.

**Comment by IH3lios** [comment]
> Update the **ytdl-core** dependency to version 0.29.2.

Worked perfectly!
