### ISSUE TITLE
After update, I have new error

### ISSUE THREAD

**Issue by xfishernet** [ytb2mp3/youtube-mp3-downloader#35]
/usr/src/node_modules/youtube-mp3-downloader/lib/YoutubeMp3Downloader.js:47
        fileName = fileName.replace(replacement[0], replacement[1]);
                            ^
TypeError: Cannot read property 'replace' of undefined
    at /usr/src/node_modules/youtube-mp3-downloader/lib/YoutubeMp3Downloader.js:47:29

**Comment by lunatine-dev** [comment]
ytdl-core changed their response in "info"
You'll have to manually change this as a temp fix.
`info = info.player_response.videoDetails;` Add this into the ytdl.getInfo function in `YoutubeMp3Downloader.js`
```ytdl.getInfo(videoUrl, function (err, info) {
		if (err) {
			callback(err.message, resultObj);
		} else {
			info = info.player_response.videoDetails;
```


This should fix your issue

**Comment by xfishernet** [comment]
thanks!

**Comment by ytb2mp3** [comment]
Version `0.6.3` was just published which should fix this. Please check, thanks for the hint @nekyoto

**Comment by xfishernet** [comment]
it's a good news! )

**Comment by ytb2mp3** [comment]
Closing, please reopen if the problem still exists.
