### ISSUE TITLE
ffmpeg exited with code 1: [something]: invalid argument

### ISSUE THREAD

**Issue by etiaro** [ytb2mp3/youtube-mp3-downloader#37]
Sometimes spaces in artist name causes this error and make download impossible, sample on this id: DyDfgMOUjCI
I've made workaround by removing spaces from artists, but i feel it's not best possible way

**Comment by Wazk** [comment]
how did you remove the spaces on the artist name?

**Comment by ytb2mp3** [comment]
@Wazk You can manually define a file name, e.g. `YD.download("Vhd6Kc4TZls", "Cold Funk - Funkorama.mp3");`

**Comment by konsti219** [comment]
@ytb2mp3 I think to problem is what pipe name is given to ffmpeg. You can use spaces in the file name without problems. There should simply be something implemented that removes all spaces(and maybe all spacial chars) from the pipe name given to ffmpeg.

**Comment by pablomuro** [comment]
And another thing, when an ffmepg error return you cant treat him cause de data parameter arrive as null

`self.YD.on("error", function(error, data) {
    if(self.callbacks[data.videoId]) {
      self.callbacks[data.videoId](error, data);
    };
  });`

`TypeError: Cannot read property 'videoId' of null`

**Comment by pablomuro** [comment]
if you pass the task on the callback and on error, you can treat the error

`self.performDownload(task, function(err, result) {
            callback(err, result, task);
        });`

**Comment by etiaro** [comment]
#38 fixes bug

**Comment by etiaro** [comment]
Okay it actually was still little buggy, this regexes  ".replace(/[^\w\s]/gi, '').replace(/[^A-Za-z0-9]+/g, '-')" propably fixes the problem, but it is a bit overkill

**Comment by uitcode** [comment]
I still get the error **ffmpeg exited with code 1: Hn: Invalid argument** with the Youtube ID **MxXKfq86E0I**

**Comment by ytb2mp3** [comment]
A bugfix was just published to nom, with version `0.6.6`. Thanks for your patience!
