### ISSUE TITLE
Can youtube block our server for using this package?

### ISSUE THREAD

**Issue by Aeyzaz** [ytb2mp3/youtube-mp3-downloader#40]
I have installed this on my server and it was working fine then suddenly it stopped working and "progress" event shows null in console

```
youtubeDownloader.on("progress", function (progress) {
                    console.log(progress.progress);
});
```

**Comment by ghost** [comment]
normally it wouldn't be that YouTube is blocking your server, but is trying to present a Captcha to your server to complete. As it's, well, a server, you can't complete the Captcha so your server never gets served the video.

This kind of package would normally work best by rotating your IPs on your server, especially if you have a block of IPv6.

**Comment by ytb2mp3** [comment]
Closing issue as it's not within the reach of this package.
