### ISSUE TITLE
Error message when used the code

### ISSUE THREAD

**Issue by reic** [ytb2mp3/youtube-mp3-downloader#44]
Could not extract html5player key: https://www.youtube.com/s/player/4fbb4d5b/player_ias.vflset/en_US/base.js

**Comment by glhrmv** [comment]
I believe this is because the `ytdl-core` dependency wasn't upgraded to the latest version.

**Comment by glhrmv** [comment]
Is there an ETA on when this might be fixed? @ytb2mp3

**Comment by ytb2mp3** [comment]
Closed with https://github.com/ytb2mp3/youtube-mp3-downloader/commit/30a25833713b5d69d28f8a5de548acb89a5e433f New version `0.6.7` was just released
