### ISSUE TITLE
Ffmpeg

### ISSUE THREAD

**Issue by horobetsb** [ytb2mp3/youtube-mp3-downloader#45]
Should i write file 'ffmpeg.exe' location in "ffmpegPath", in constructor, or just its folder? Both not working(

**Comment by ssjlin9999** [comment]
Step 1: Find your 'ffmpeg.exe' file location
<img width="509" alt="ffmpeg" src="https://user-images.githubusercontent.com/60172395/80174715-19537300-8626-11ea-9f88-a97913c6a221.png">

Step 2: Try this.
**"ffmpegPath": "D:/ffmpeg-20200422-2e38c63-win64-static/bin/ffmpeg",** 
```
//Configure YoutubeMp3Downloader with your settings
const YD = new youtubeMp3Downloader({
    "ffmpegPath": "D:/ffmpeg-20200422-2e38c63-win64-static/bin/ffmpeg",        // Where is the FFmpeg binary located?
    "outputPath": "./",                     // Where should the downloaded and encoded files be stored?
    "youtubeVideoQuality": "highest",       // What video quality should be used?
    "queueParallelism": 2,                  // How many parallel downloads/encodes should be started?
    "progressTimeout": 2000                 // How long should be the interval of the progress reports
});
```

**Comment by horobetsb** [comment]
Thanks) It works now)

**Comment by ytb2mp3** [comment]
Closing issue as solved. Thanks @SunnyLin9999
