### ISSUE TITLE
Display DL progress to user

### ISSUE THREAD

**Issue by l0rddarkf0rce** [ytb2mp3/youtube-mp3-downloader#46]
I wrote a simple node.js app that takes a youtube url, downloads the mp3 and then sends it to the user. The download seems to work OK, but I would like to display the completion percentage on the user's browser (more than anything so that they don't think that nothing is happening).  Is this even possible?  TIA

**Comment by ytb2mp3** [comment]
If you mean via a Node.js backend for a website, then the most common way would be to use WebSockets to send the updates to the browser.
