### ISSUE TITLE
How will it work if i deploy my app to heroku

### ISSUE THREAD

**Issue by VIRGO96** [ytb2mp3/youtube-mp3-downloader#47]
FFMPEG is in my local machine how will it work when i deploy it on heroku kindly help

**Comment by ytb2mp3** [comment]
Seems like there a build pack for FFMPEG: https://elements.heroku.com/buildpacks/fluent-ffmpeg/node-fluent-ffmpeg#buildpack-instructions I can't do support for every use case unfortunately, so please have a look yourself.

**Comment by VIRGO96** [comment]
Thank you what i needed was if you could guide me on how could we set path like locally we give a path to drive for ffmpeg but what about heroku server what would the path be then
