### ISSUE TITLE
youtube-mp3-downloader npm not working for the youtube ID -> 60ItHLz5WEA .

### ISSUE THREAD

**Issue by vikram-sapate** [ytb2mp3/youtube-mp3-downloader#48]
Hey, 
I just tried to download this famous song named faded 
https://www.youtube.com/watch?v=60ItHLz5WEA

`var YoutubeMp3Downloader = require("youtube-mp3-downloader");
const config = require('./config/config.js');

//Configure YoutubeMp3Downloader with your settings
var YD = new YoutubeMp3Downloader({
  "ffmpegPath": config.ffmpegPath,
  "outputPath": config.outputPath,
  "youtubeVideoQuality": config.youtubeVideoQuality,
  "queueParallelism": config.queueParallelism,
  "progressTimeout": config.progressTimeout
});
 
//Download video and save as MP3 file
YD.download("60ItHLz5WEA");
 
YD.on("finished", function(err, data) {
    console.log(JSON.stringify(data));
});
 
YD.on("error", function(error) {
    console.log(error);
});

YD.on("progress", function(progress) {
    console.log(JSON.stringify(progress));
});`

But it is throwing following error

url.js:154
    throw new ERR_INVALID_ARG_TYPE('url', 'string', url);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at Url.parse (url.js:154:11)
    at Object.urlParse [as parse] (url.js:148:13)
    at doDownload (...\node_modules\miniget\dist\index.js:90:28)
    at process._tickCallback (internal/process/next_tick.js:61:11)

Please help

Note that code works well for all other ids

**Comment by 1rosehip** [comment]
The same issue with IDs "BYW856tViUM", "VUjdiDeJ0xg", "5zk5y-eczY8" and others.

**Comment by rockxwre** [comment]
Same issue with https://www.youtube.com/watch?v=B0xUPnapNyM as well.
Can be solved by upgrading ytdl-core to version 2.1.7.
See also https://github.com/rockxwre/youtube-mp3-downloader/commit/fc5bd7807ab3002f9aae83a7c761a68b6f7d62fc

**Comment by ytb2mp3** [comment]
This was closed in 28dacf6c4141af4e8a9ec0fecb4388f1689198b8. Please use version `0.6.8`

**Comment by vikram-sapate** [comment]
Thanks @rockxwre

**Comment by matthew-kerle** [comment]
@ytb2mp3 I don't see a version `0.6.8` released yet. Can you publish it?

**Comment by tobilg** [comment]
https://www.npmjs.com/package/youtube-mp3-downloader

**Comment by matthew-kerle** [comment]
> https://www.npmjs.com/package/youtube-mp3-downloader

Yeah, but would be nice on GH too.
