### ISSUE TITLE
Status code: 429 on videoId 60ItHLz5WEA

### ISSUE THREAD

**Issue by therevolt** [ytb2mp3/youtube-mp3-downloader#49]
Hi,
I found a new issue

> Status code: 429 on videoId 60ItHLz5WEA

**Comment by vikram-sapate** [comment]
Try this
**npm install ytdl-core@latest**
Internally **youtube-mp3-downloader** uses ytdl-core.
If it's not solved refer [https://github.com/fent/node-ytdl-core#what-if-it-stops-working](url)

**Comment by ytb2mp3** [comment]
Closed via #50
