### ISSUE TITLE
Some videos are not downloading

### ISSUE THREAD

**Issue by ElMoustacho** [ytb2mp3/youtube-mp3-downloader#53]
Most videos are downloadable but sometimes when I start a download the video doesn't download and no error message triggers

**Comment by ytb2mp3** [comment]
Please add some example videos ids which don't work. Thanks...

**Comment by husek** [comment]
Just ran into a video with the same behaviour, I'll investigate nonetheless, id: QjZwuimMb3M

**Comment by husek** [comment]
@ytb2mp3 there you go.
