### ISSUE TITLE
Error parsing config

### ISSUE THREAD

**Issue by Surik266** [ytb2mp3/youtube-mp3-downloader#54]
Does not load any videos 
`Error parsing config: Unexpected token ; in JSON at position 186786`
<img width="686" alt="Screen Shot 2020-07-30 at 07 16 26" src="https://user-images.githubusercontent.com/39604676/88876571-9c432580-d234-11ea-817e-922679af2384.png">

**Comment by ytb2mp3** [comment]
I just released version 0.7.2, please try again.

**Comment by Xh4H** [comment]
> I just released version 0.7.2, please try again.

Works for me now, thank you!
