### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by mandazi** [ytb2mp3/youtube-mp3-downloader#6]
I am trying to run it with the example provided but I am getting this error:

$ node index
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:874:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:339:9)
    at /project/node_modules/youtube-mp3-downloader/node_modules/fluent-ffmpeg/lib/processor.js:135:24
    at FfmpegCommand.proto._getFfmpegPath (/project/node_modules/youtube-mp3-downloader/node_modules/fluent-ffmpeg/lib/capabilities.js:90:14)
    at FfmpegCommand.proto._spawnFfmpeg (/project/node_modules/youtube-mp3-downloader/node_modules/fluent-ffmpeg/lib/processor.js:115:10)
    at FfmpegCommand.proto.availableFormats.proto.getAvailableFormats (/project/node_modules/youtube-mp3-downloader/node_modules/fluent-ffmpeg/lib/capabilities.js:514:10)
    at /project/node_modules/youtube-mp3-downloader/node_modules/fluent-ffmpeg/lib/capabilities.js:564:14
    at fn (/project/node_modules/youtube-mp3-downloader/node_modules/async/lib/async.js:716:34)
    at /project/node_modules/youtube-mp3-downloader/node_modules/async/lib/async.js:1169:16

**Comment by tobilg** [comment]
Which version of FFMpeg are you using?

**Comment by mandazi** [comment]
@tobilg  - Version 2.6.1

**Comment by tobilg** [comment]
I'm using the exact same version. Make sure the files/folder(s) have the right permissions, e.g. `chmod +x *.js`

**Comment by mandazi** [comment]
I am not sure what the right permissions should be and for what directories.
I installed ffmpeg via Homebrew.  It is located here:
    "ffmpegPath": "/usr/local/Cellar/ffmpeg/2.6.1/bin/"

These are the permissions for my node app which is just the example trying to download the mp3 of a youtube video:

$ ls -l
total 16
-rwxr-xr-x@ 1 amir  staff  905 Oct 17 22:02 index.js
drwxr-xr-x@ 4 amir  staff  136 Oct 17 21:46 node_modules
-rw-r--r--@ 1 amir  staff  186 Oct 17 21:44 package.json

This is the permissions of the ffmpeg folder (/usr/local/Cellar/ffmpeg/2.6.1/):
$ ls -l
total 120
-rw-r--r--   1 amir  admin  48602 Mar 16  2015 Changelog
-rw-r--r--   1 amir  admin    808 Oct 17 21:54 INSTALL_RECEIPT.json
-rw-r--r--   1 amir  admin   3845 Mar 16  2015 LICENSE.md
-rw-r--r--   1 amir  admin   1654 Mar 16  2015 README.md
drwxr-xr-x   5 amir  admin    170 Mar 17  2015 bin
drwxr-xr-x  11 amir  admin    374 Mar 17  2015 include
drwxr-xr-x  39 amir  admin   1326 Mar 17  2015 lib
drwxr-xr-x   5 amir  admin    170 Mar 17  2015 share

**Comment by tobilg** [comment]
Probably it's sufficient to run `sudo chmod +x index.js`.

**Comment by mandazi** [comment]
I ran the command `sudo chmod +x index.js` and after that I ran `node index` and still received the same original error.

I believe this might be the way ffmpeg is installed.  How did you install ffmpeg?

**Comment by tobilg** [comment]
I installed it also with Homebrew

**Comment by mandazi** [comment]
I got it to work.  Looks my path was wrong.  It should have been this:
"ffmpegPath": "/usr/local/bin/ffmpeg"
