### ISSUE TITLE
Respond Error

### ISSUE THREAD

**Issue by brillyandev** [ytb2mp3/youtube-mp3-downloader#60]
How To Fix..

 Error [ERR_UNHANDLED_ERROR]: Unhandled error. ('Status code: 429')

Please, Help Me.

**Comment by fdciabdul** [comment]
check the video , make sure the video isn't private , age limit , and blocked

**Comment by brillyandev** [comment]
How to fix

**Comment by brillyandev** [comment]
The video doesn't violate what you say. I just want to request a song to mp3

**Comment by tobilg** [comment]
You seem to get throttled by the YouTube API / Website: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429

**Comment by brillyandev** [comment]
@tobilg #SOLVED Thanks Bro.
