### ISSUE TITLE
Not working for video ID bNymC_F9wpo

### ISSUE THREAD

**Issue by vikram-sapate** [ytb2mp3/youtube-mp3-downloader#69]
Hi,

It's not working with video  https://www.youtube.com/watch?v=bNymC_F9wpo
Because  info.formats[0].audioBitrate is null .........line no 147 (YoutubeMp3Downloader.js)

Please look into it, What's happening.

**Comment by ytb2mp3** [comment]
Please try with the version `0.7.5` that was released today.

**Comment by vikram-sapate** [comment]
Thanks @ytb2mp3
