### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by qaraluch** [ytb2mp3/youtube-mp3-downloader#7]
Update dependencies, please.
Especially ytdl-core.

**Comment by tobilg** [comment]
Can you please specify problems you're having?

**Comment by qaraluch** [comment]
Due to outdated ytdl-core some vids throw error: "could not extract signature decipheri
ng actions", specified [here](https://github.com/fent/node-ytdl-core/issues/58).

**Comment by tobilg** [comment]
Thanks, I'll have a look later today.

**Comment by tobilg** [comment]
Merged. Thanks for the pull request.

**Comment by tobilg** [comment]
I also put a new release on NPM (v0.3.6).

**Comment by qaraluch** [comment]
Thx.
