### ISSUE TITLE
IYoutubeMp3DownloaderOptions type missing properties

### ISSUE THREAD

**Issue by mpirescarvalho** [ytb2mp3/youtube-mp3-downloader#71]
Cannot set `requestOptions` because it's missing in type definitions

![image](https://user-images.githubusercontent.com/20830847/100164015-bd8be980-2e95-11eb-927d-5b69db58d99c.png)

Should I submit a PR fixing it?

**Comment by ytb2mp3** [comment]
Feel free to create a PR with the respective changes, thanks!

**Comment by mpirescarvalho** [comment]
ok
