### ISSUE TITLE
self signed certificate in certificate chain

### ISSUE THREAD

**Issue by mouragilvan** [ytb2mp3/youtube-mp3-downloader#74]
When i call 

YD.on("error", function(error) {
    console.log("erro aqui",error);
});

returning this error: self signed certificate in certificate chain

**Comment by ytb2mp3** [comment]
Seems to be a local issue. What exactly are you trying to achieve?

**Comment by mouragilvan** [comment]
When i try, is returning this error:  UnhandledPromiseRejectionWarning: Error: self signed certificate in certificate chain

**Comment by cwienands1** [comment]
@mouragilvan I assume you are behind a company proxy that transparently decrypts and re-encrypts all web traffic. You can tell by looking at the certificate chain when you navigate to pages like https://google.com or https://cnn.com. Chances are, the root certificate at the top of the chain is a CA cert self-signed by your company, or by one of the web monitoring providers like goskope.

I solved this problem on my Windows machine by using the `win-ca` package. See https://www.npmjs.com/package/win-ca
