### ISSUE TITLE
ffmpeg spawn issue: spawn EN0TDIR

### ISSUE THREAD

**Issue by matthew-kerle** [ytb2mp3/youtube-mp3-downloader#77]
Only occurs in production when bundled in an electron app. Yes, I have the ffmpeg binaries included and set with `ffmpegPath`, I also have it installed on my computer in bin as a fallback. Any ideas? Works flawlessly in dev.

<img width="901" alt="Screen Shot 2021-01-02 at 7 51 40 PM" src="https://user-images.githubusercontent.com/648400/103470989-46206400-4d37-11eb-91ce-b28de5329e00.png">

**Comment by matthew-kerle** [comment]
Just bumping this, any help @ytb2mp3 ?

**Comment by ytb2mp3** [comment]
Sorry, I have no experience with Electron production builds.
