### ISSUE TITLE
videoDetails.thumbnail.thumbnails` will be removed in a near future release, use `videoDetails.thumbnails` instead

### ISSUE THREAD

**Issue by vikram-sapate** [ytb2mp3/youtube-mp3-downloader#79]
How to remove this warning "**videoDetails.thumbnail.thumbnails** will be removed in a near future release, use **videoDetails.thumbnails**" ??????
Each time I use **youtube-mp3-downloader** , this warning is coming on the console.

**Comment by nehoraigold** [comment]
I saw this too, so I opened a [pull request](https://github.com/ytb2mp3/youtube-mp3-downloader/pull/80) for it.

**Comment by ytb2mp3** [comment]
Fixed by #80
