### ISSUE TITLE
"yvRg9m24fYo" video cant be downloaded

### ISSUE THREAD

**Issue by DeveloperOskar** [ytb2mp3/youtube-mp3-downloader#82]
Hi i am trying to download this video "yvRg9m24fYo" , but it do not work. The process just stands and nothing happens....

I am logging the progress, and error, but the process never starts with this video. And i dont get any errors. Any one have any ide about this bugg ?  

It works fine with every other video i try, but this one just dont work...

**Comment by stephengeorge568** [comment]
Is there a time constraint? Your video is ~ 1.5 hours.

**Comment by DeveloperOskar** [comment]
I have abandon the project, but I dont think do since alot of the videos that are working are around the same length... but that one might have crossed the limit on length, but where can you find the maximum download length?
