### ISSUE TITLE
On 100%: ffmpeg exited with code 1: Output #0 ... Output file #0 does not contain any stream

### ISSUE THREAD

**Issue by anzem** [ytb2mp3/youtube-mp3-downloader#88]
Reproducible with basic example and video ID "JPL7sgr7pco".  Error throws on progress 100%.
Works with other IDs, any way to catch this and skip?

**Comment by ytb2mp3** [comment]
Works with the about to be released `v0.7.8` in local tests. Please check and reopen if this persists.
