### ISSUE TITLE
problem with progress event after update

### ISSUE THREAD

**Issue by qaraluch** [ytb2mp3/youtube-mp3-downloader#9]
Something bad happened with progress event during recent update, I guess. 

```
{ videoId: 'aflmCuUfq-I',
  progress:
   { percentage: 0,
     transferred: 6275788,
     length: 0,
     remaining: 0,
     eta: 0,
     runtime: 3,
     delta: 2719728,
     speed: 1793082.2857142857 } }
```

Emitted object has wrong  percentage, length, remaining and eta values.
Please check it out cause I can not figure it out what wrong happened.

**Comment by tobilg** [comment]
The ytdl API has changed. I pushed a new release (0.4.0). Please check.

**Comment by qaraluch** [comment]
It's working smoothly, now. Thanks for update.
